name: Build

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
        
    - name: Build Zeek Docker image
      run: |
        docker build -t zeek:zeek .

    - name: Create Zeek Docker container
      run: |
        docker run -d zeek:zeek

