name: Build

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
        
    - name: Docker build of Zeek
      run: |
        docker build -t zeek:zeek .